#!/usr/bin/env bash
  sudo bash <<LEVEL2SCRIPT
  set -e
  cd \$HOME
  export DEBIAN_FRONTEND=noninteractive
  apt-get -y --reinstall install aptitude
  aptitude -y install build-essential
  aptitude -y install python3 python3-dev python3-pip
  aptitude -y install python python-dev python-pip
  aptitude -y install software-properties-common
  add-apt-repository -y ppa:pi-rho/dev
  cat > /etc/apt/preferences.d/pi-rho-dev <<EOFL
Package: *
Pin: release o=LP-PPA-pi-rho-dev
Pin-Priority: 400

Package: vim*
Pin: release o=LP-PPA-pi-rho-dev
Pin-Priority: 500
EOFL
  aptitude -y update
  aptitude -y install curl
  # Packages are complaining about old zmq
  # Let pyzmq use its own zmq
  # aptitude -y install libzmq-dev
  aptitude -y install libsox-dev sox gfortran libopenblas-dev liblapack-dev alsa-base
  aptitude -y install git clang libclang1 exuberant-ctags tmux libclang-dev
  aptitude -y install vim-nox
  # Matplotlib build depends (matplotlib not available for python3 on ubuntu)
  aptitude -y install libpng-dev libfreetype6-dev libgtk2.0-dev librsvg2-dev
  aptitude -y install --without-recommends texlive texlive-latex-extra pgf
  aptitude -y install dvipng pandoc python3-pyside
  aptitude -y install python-pyside
  aptitude -y install cmake libqt4-dev libxml2-dev libxslt1-dev qtmobility-dev
  # Clean up
  apt-get autoremove
  aptitude -y clean
  aptitude -y autoclean
  bash rebuild-pip-packages
  # pip will be cleaned because it works in temp
  rm -rf distribute-*.tar.gz
  rm -rf src
  rm -rf postinstall.sh
  ldconfig
LEVEL2SCRIPT

