#!/usr/bin/env bash

rm -rf --one-file-system python3pylab
set -e
UMIRROR=`curl -s http://mirrors.ubuntu.com/mirrors.txt | head -n 1`
debootstrap --variant=buildd --arch amd64 raring python3pylab $UMIRROR
mount --rbind /dev python3pylab/dev
mount --rbind /proc python3pylab/proc
mount --rbind /sys python3pylab/sys
mount --rbind /run python3pylab/run
mount --rbind /tmp python3pylab/tmp
cp sources.list python3pylab/etc/apt
chroot python3pylab su <<SCRIPT
  set -e
  export DEBIAN_FRONTEND=noninteractive
  # Safe update
  apt-get -y update
  apt-get -y install sudo locales aptitude
  locale-gen en_US.utf8
  aptitude -y safe-upgrade
  ldconfig
SCRIPT
mkdir -p python3pylab/vagrant
cp build_pyside python3pylab/vagrant
chroot python3pylab su < rebuild-packages
chroot python3pylab aptitude -y update
chroot python3pylab ldconfig
