#!/usr/bin/env bash

#It should be possible to enable this, when everything works fine
#set -e
vagrant destroy
vagrant up
vagrant ssh <<SCRIPT
  set -e
  export DEBIAN_FRONTEND=noninteractive
  cp /etc/apt/sources.list /etc/apt/sources.list.old.pylab
  # Enabling mirrors
  echo deb mirror://mirrors.ubuntu.com/mirrors.txt precise main restricted universe multiverse > /etc/apt/sources.list
  echo deb mirror://mirrors.ubuntu.com/mirrors.txt precise-updates main restricted universe multiverse >> /etc/apt/sources.list
  echo deb mirror://mirrors.ubuntu.com/mirrors.txt precise-backports main restricted universe multiverse >> /etc/apt/sources.list
  echo deb mirror://mirrors.ubuntu.com/mirrors.txt precise-security main restricted universe multiverse >> /etc/apt/sources.list
  echo >> /etc/apt/sources.list
  cat < /etc/apt/sources.list.old.pylab >> /etc/apt/sources.list
  # Full update
  aptitude -y update
  aptitude -y full-upgrade
SCRIPT
vagrant halt
vagrant up --no-provision
vagrant ssh <<SCRIPT
  set -e
  export DEBIAN_FRONTEND=noninteractive
  aptitude -y install build-essential
  aptitude -y install python3
  aptitude -y install python3-dev
  aptitude -y install curl
  aptitude -y install cmake
  aptitude -y install libzmq-dev
  aptitude -y install libqt4-dev
  aptitude -y install libqt4-opengl-dev
  # Clean up
  aptitude -y clean
  aptitude -y autoclean
  # Install pip
  curl http://python-distribute.org/distribute_setup.py | python3
  curl https://raw.github.com/pypa/pip/master/contrib/get-pip.py | python3
  # Python tools
  pip-3.2 install pyside
  # Pip will be cleaned by reboot since it works in /tmp
SCRIPT
vagrant halt
vagrant up --no-provision
vagrant ssh <<SCRIPT
  dd if=/dev/zero of=/tmp/zero.pylab bs=2048
  sync
  rm /tmp/zero.pylab
  sync
SCRIPT
vagrant halt
HDDID=`VBoxManage showvminfo python3pylab --machinereadable | \
     grep "SATA Controller-ImageUUID-" | cut -d = -f 2 | tr -d \"`
HDDFILE=`VBoxManage showvminfo python3pylab --machinereadable | \
     grep "SATA Controller-" | grep -v -- "-ImageUUID-" | cut -d = -f 2 | tr -d \"`
VBoxManage clonehd "$HDDID" ./out.vmdk
VBoxManage internalcommands sethduuid ./out.vmdk "$HDDID"
mv ./out.vmdk "$HDDFILE"
