#!/usr/bin/env bash
# Typical cron entry
# @reboot HOME=/home/ganwell USER=ganwell /home/ganwell/prj/vagrant-pylab-build/start-chroot
# PATH is set for start from cron
PATH="$PATH:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
MAIN_DIR="$( dirname $(cd ${0%/*} && echo $PWD/${0##*/}) )"
CHROOT_HOME="$MAIN_DIR/pylab3chroot/$HOME"
cp /etc/passwd "$MAIN_DIR/pylab3chroot/etc/"
cp /etc/group "$MAIN_DIR/pylab3chroot/etc/"
touch "$HOME/.chroothome"
if [ ! -f "$CHROOT_HOME/.chroothome" ]; then
	echo Bind home
	mkdir -p "$CHROOT_HOME"
	mount --rbind "$HOME" "$CHROOT_HOME"
	mount --rbind /dev "$MAIN_DIR/pylab3chroot/dev"
	mount --rbind /proc "$MAIN_DIR/pylab3chroot/proc"
	mount --rbind /sys "$MAIN_DIR/pylab3chroot/sys"
	mount --rbind /run "$MAIN_DIR/pylab3chroot/run"
	mount --rbind /tmp "$MAIN_DIR/pylab3chroot/tmp"
fi
chroot --userspec=ganwell "$MAIN_DIR/pylab3chroot" <<SCRIPT
cd
mkdir -p notebooks
cd notebooks
ipython3 notebook --no-browser
SCRIPT

